baseURL = 'https://intelligence.dev/'
languageCode = 'en-us'
title = 'intelligence.dev'
theme = 'PaperMod'

[params]
  author = "Manifold"
  description = "The intelligence.dev website for Manifold."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10
